// Code generated by MockGen. DO NOT EDIT.
// Source: ../utils/config.go
//
// Generated by this command:
//
//	mockgen -package mock -source ../utils/config.go -destination ../mock/mock_config.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	common "github.com/kweaver-ai/kweaver-core/adp/dataflow/flow-automation/pkg/ecron/common"
	gomock "go.uber.org/mock/gomock"
)

// MockConfiger is a mock of Configer interface.
type MockConfiger struct {
	ctrl     *gomock.Controller
	recorder *MockConfigerMockRecorder
	isgomock struct{}
}

// MockConfigerMockRecorder is the mock recorder for MockConfiger.
type MockConfigerMockRecorder struct {
	mock *MockConfiger
}

// NewMockConfiger creates a new mock instance.
func NewMockConfiger(ctrl *gomock.Controller) *MockConfiger {
	mock := &MockConfiger{ctrl: ctrl}
	mock.recorder = &MockConfigerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfiger) EXPECT() *MockConfigerMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockConfiger) Config() common.ConfigLoader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(common.ConfigLoader)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockConfigerMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockConfiger)(nil).Config))
}

// Lang mocks base method.
func (m *MockConfiger) Lang() common.LangLoader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lang")
	ret0, _ := ret[0].(common.LangLoader)
	return ret0
}

// Lang indicates an expected call of Lang.
func (mr *MockConfigerMockRecorder) Lang() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lang", reflect.TypeOf((*MockConfiger)(nil).Lang))
}
