// Code generated by MockGen. DO NOT EDIT.
// Source: ../utils/auth.go
//
// Generated by this command:
//
//	mockgen -package mock -source ../utils/auth.go -destination ../mock/mock_auth.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	common "github.com/kweaver-ai/kweaver-core/adp/dataflow/flow-automation/pkg/ecron/common"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthClient is a mock of OAuthClient interface.
type MockOAuthClient struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthClientMockRecorder
	isgomock struct{}
}

// MockOAuthClientMockRecorder is the mock recorder for MockOAuthClient.
type MockOAuthClientMockRecorder struct {
	mock *MockOAuthClient
}

// NewMockOAuthClient creates a new mock instance.
func NewMockOAuthClient(ctrl *gomock.Controller) *MockOAuthClient {
	mock := &MockOAuthClient{ctrl: ctrl}
	mock.recorder = &MockOAuthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthClient) EXPECT() *MockOAuthClientMockRecorder {
	return m.recorder
}

// GetCode mocks base method.
func (m *MockOAuthClient) GetCode(secret string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCode", secret)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCode indicates an expected call of GetCode.
func (mr *MockOAuthClientMockRecorder) GetCode(secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCode", reflect.TypeOf((*MockOAuthClient)(nil).GetCode), secret)
}

// GetSecret mocks base method.
func (m *MockOAuthClient) GetSecret() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockOAuthClientMockRecorder) GetSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockOAuthClient)(nil).GetSecret))
}

// Release mocks base method.
func (m *MockOAuthClient) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockOAuthClientMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockOAuthClient)(nil).Release))
}

// RequestToken mocks base method.
func (m *MockOAuthClient) RequestToken(id, secret string, scope []string) (string, time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestToken", id, secret, scope)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Duration)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RequestToken indicates an expected call of RequestToken.
func (mr *MockOAuthClientMockRecorder) RequestToken(id, secret, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestToken", reflect.TypeOf((*MockOAuthClient)(nil).RequestToken), id, secret, scope)
}

// VerifyCode mocks base method.
func (m *MockOAuthClient) VerifyCode(secret, code string) (bool, *common.ECronError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCode", secret, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*common.ECronError)
	return ret0, ret1
}

// VerifyCode indicates an expected call of VerifyCode.
func (mr *MockOAuthClientMockRecorder) VerifyCode(secret, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCode", reflect.TypeOf((*MockOAuthClient)(nil).VerifyCode), secret, code)
}

// VerifyHydraVersion mocks base method.
func (m *MockOAuthClient) VerifyHydraVersion() (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyHydraVersion")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// VerifyHydraVersion indicates an expected call of VerifyHydraVersion.
func (mr *MockOAuthClientMockRecorder) VerifyHydraVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyHydraVersion", reflect.TypeOf((*MockOAuthClient)(nil).VerifyHydraVersion))
}

// VerifyToken mocks base method.
func (m *MockOAuthClient) VerifyToken(token string) (common.Visitor, *common.ECronError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", token)
	ret0, _ := ret[0].(common.Visitor)
	ret1, _ := ret[1].(*common.ECronError)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockOAuthClientMockRecorder) VerifyToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockOAuthClient)(nil).VerifyToken), token)
}
