// Code generated by MockGen. DO NOT EDIT.
// Source: ../utils/sql.go
//
// Generated by this command:
//
//	mockgen -package mock -source ../utils/sql.go -destination ../mock/mock_sql.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	common "github.com/kweaver-ai/kweaver-core/adp/dataflow/flow-automation/pkg/ecron/common"
	gomock "go.uber.org/mock/gomock"
)

// MockSQLFactory is a mock of SQLFactory interface.
type MockSQLFactory struct {
	ctrl     *gomock.Controller
	recorder *MockSQLFactoryMockRecorder
	isgomock struct{}
}

// MockSQLFactoryMockRecorder is the mock recorder for MockSQLFactory.
type MockSQLFactoryMockRecorder struct {
	mock *MockSQLFactory
}

// NewMockSQLFactory creates a new mock instance.
func NewMockSQLFactory(ctrl *gomock.Controller) *MockSQLFactory {
	mock := &MockSQLFactory{ctrl: ctrl}
	mock.recorder = &MockSQLFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLFactory) EXPECT() *MockSQLFactoryMockRecorder {
	return m.recorder
}

// AddConditionSQL mocks base method.
func (m *MockSQLFactory) AddConditionSQL(condition *string, field, judge string, value any, args *[]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddConditionSQL", condition, field, judge, value, args)
}

// AddConditionSQL indicates an expected call of AddConditionSQL.
func (mr *MockSQLFactoryMockRecorder) AddConditionSQL(condition, field, judge, value, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConditionSQL", reflect.TypeOf((*MockSQLFactory)(nil).AddConditionSQL), condition, field, judge, value, args)
}

// AddLimitSQL mocks base method.
func (m *MockSQLFactory) AddLimitSQL(condition *string, limit, page int, args *[]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddLimitSQL", condition, limit, page, args)
}

// AddLimitSQL indicates an expected call of AddLimitSQL.
func (mr *MockSQLFactoryMockRecorder) AddLimitSQL(condition, limit, page, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLimitSQL", reflect.TypeOf((*MockSQLFactory)(nil).AddLimitSQL), condition, limit, page, args)
}

// AddOrderBySQL mocks base method.
func (m *MockSQLFactory) AddOrderBySQL(condition *string, fields map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddOrderBySQL", condition, fields)
}

// AddOrderBySQL indicates an expected call of AddOrderBySQL.
func (mr *MockSQLFactoryMockRecorder) AddOrderBySQL(condition, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrderBySQL", reflect.TypeOf((*MockSQLFactory)(nil).AddOrderBySQL), condition, fields)
}

// AddWhereSQL mocks base method.
func (m *MockSQLFactory) AddWhereSQL(condition *string, args *[]any) (string, []any) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWhereSQL", condition, args)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	return ret0, ret1
}

// AddWhereSQL indicates an expected call of AddWhereSQL.
func (mr *MockSQLFactoryMockRecorder) AddWhereSQL(condition, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWhereSQL", reflect.TypeOf((*MockSQLFactory)(nil).AddWhereSQL), condition, args)
}

// BatchJobEnableSQL mocks base method.
func (m *MockSQLFactory) BatchJobEnableSQL(fields, jobID []string, visitor common.Visitor) (string, []any) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchJobEnableSQL", fields, jobID, visitor)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	return ret0, ret1
}

// BatchJobEnableSQL indicates an expected call of BatchJobEnableSQL.
func (mr *MockSQLFactoryMockRecorder) BatchJobEnableSQL(fields, jobID, visitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchJobEnableSQL", reflect.TypeOf((*MockSQLFactory)(nil).BatchJobEnableSQL), fields, jobID, visitor)
}

// BatchJobNotifyQuerySQL mocks base method.
func (m *MockSQLFactory) BatchJobNotifyQuerySQL(jobID []string) (string, []any) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchJobNotifyQuerySQL", jobID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	return ret0, ret1
}

// BatchJobNotifyQuerySQL indicates an expected call of BatchJobNotifyQuerySQL.
func (mr *MockSQLFactoryMockRecorder) BatchJobNotifyQuerySQL(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchJobNotifyQuerySQL", reflect.TypeOf((*MockSQLFactory)(nil).BatchJobNotifyQuerySQL), jobID)
}

// BatchJobNotifyUpdateSQL mocks base method.
func (m *MockSQLFactory) BatchJobNotifyUpdateSQL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchJobNotifyUpdateSQL")
	ret0, _ := ret[0].(string)
	return ret0
}

// BatchJobNotifyUpdateSQL indicates an expected call of BatchJobNotifyUpdateSQL.
func (mr *MockSQLFactoryMockRecorder) BatchJobNotifyUpdateSQL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchJobNotifyUpdateSQL", reflect.TypeOf((*MockSQLFactory)(nil).BatchJobNotifyUpdateSQL))
}

// CheckJobIDExistSQL mocks base method.
func (m *MockSQLFactory) CheckJobIDExistSQL(fields, jobID []string, visitor common.Visitor) (string, []any) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckJobIDExistSQL", fields, jobID, visitor)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	return ret0, ret1
}

// CheckJobIDExistSQL indicates an expected call of CheckJobIDExistSQL.
func (mr *MockSQLFactoryMockRecorder) CheckJobIDExistSQL(fields, jobID, visitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckJobIDExistSQL", reflect.TypeOf((*MockSQLFactory)(nil).CheckJobIDExistSQL), fields, jobID, visitor)
}

// CheckJobNameSQL mocks base method.
func (m *MockSQLFactory) CheckJobNameSQL(fields []string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckJobNameSQL", fields)
	ret0, _ := ret[0].(string)
	return ret0
}

// CheckJobNameSQL indicates an expected call of CheckJobNameSQL.
func (mr *MockSQLFactoryMockRecorder) CheckJobNameSQL(fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckJobNameSQL", reflect.TypeOf((*MockSQLFactory)(nil).CheckJobNameSQL), fields)
}

// DeleteJobSQL mocks base method.
func (m *MockSQLFactory) DeleteJobSQL(fields, jobID []string, visitor common.Visitor) (string, []any) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJobSQL", fields, jobID, visitor)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	return ret0, ret1
}

// DeleteJobSQL indicates an expected call of DeleteJobSQL.
func (mr *MockSQLFactoryMockRecorder) DeleteJobSQL(fields, jobID, visitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJobSQL", reflect.TypeOf((*MockSQLFactory)(nil).DeleteJobSQL), fields, jobID, visitor)
}

// DeletedJobStatusQuerySQL mocks base method.
func (m *MockSQLFactory) DeletedJobStatusQuerySQL(jobID []string) (string, []any) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletedJobStatusQuerySQL", jobID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	return ret0, ret1
}

// DeletedJobStatusQuerySQL indicates an expected call of DeletedJobStatusQuerySQL.
func (mr *MockSQLFactoryMockRecorder) DeletedJobStatusQuerySQL(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletedJobStatusQuerySQL", reflect.TypeOf((*MockSQLFactory)(nil).DeletedJobStatusQuerySQL), jobID)
}

// DeletedJobStatusUpdateSQL mocks base method.
func (m *MockSQLFactory) DeletedJobStatusUpdateSQL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletedJobStatusUpdateSQL")
	ret0, _ := ret[0].(string)
	return ret0
}

// DeletedJobStatusUpdateSQL indicates an expected call of DeletedJobStatusUpdateSQL.
func (mr *MockSQLFactoryMockRecorder) DeletedJobStatusUpdateSQL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletedJobStatusUpdateSQL", reflect.TypeOf((*MockSQLFactory)(nil).DeletedJobStatusUpdateSQL))
}

// GetFindInSetSQL mocks base method.
func (m *MockSQLFactory) GetFindInSetSQL(value any) (string, []any) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFindInSetSQL", value)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	return ret0, ret1
}

// GetFindInSetSQL indicates an expected call of GetFindInSetSQL.
func (mr *MockSQLFactoryMockRecorder) GetFindInSetSQL(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFindInSetSQL", reflect.TypeOf((*MockSQLFactory)(nil).GetFindInSetSQL), value)
}

// GetJobSQL mocks base method.
func (m *MockSQLFactory) GetJobSQL(fields []string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobSQL", fields)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetJobSQL indicates an expected call of GetJobSQL.
func (mr *MockSQLFactoryMockRecorder) GetJobSQL(fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobSQL", reflect.TypeOf((*MockSQLFactory)(nil).GetJobSQL), fields)
}

// GetJobStatusSQL mocks base method.
func (m *MockSQLFactory) GetJobStatusSQL(fields []string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobStatusSQL", fields)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetJobStatusSQL indicates an expected call of GetJobStatusSQL.
func (mr *MockSQLFactoryMockRecorder) GetJobStatusSQL(fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobStatusSQL", reflect.TypeOf((*MockSQLFactory)(nil).GetJobStatusSQL), fields)
}

// GetJobTotalSQL mocks base method.
func (m *MockSQLFactory) GetJobTotalSQL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobTotalSQL")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetJobTotalSQL indicates an expected call of GetJobTotalSQL.
func (mr *MockSQLFactoryMockRecorder) GetJobTotalSQL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobTotalSQL", reflect.TypeOf((*MockSQLFactory)(nil).GetJobTotalSQL))
}

// GetUpdateJobStatusInsertSQL mocks base method.
func (m *MockSQLFactory) GetUpdateJobStatusInsertSQL(fields, set []string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdateJobStatusInsertSQL", fields, set)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUpdateJobStatusInsertSQL indicates an expected call of GetUpdateJobStatusInsertSQL.
func (mr *MockSQLFactoryMockRecorder) GetUpdateJobStatusInsertSQL(fields, set any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdateJobStatusInsertSQL", reflect.TypeOf((*MockSQLFactory)(nil).GetUpdateJobStatusInsertSQL), fields, set)
}

// GetUpdateJobStatusQuerySQL mocks base method.
func (m *MockSQLFactory) GetUpdateJobStatusQuerySQL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdateJobStatusQuerySQL")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUpdateJobStatusQuerySQL indicates an expected call of GetUpdateJobStatusQuerySQL.
func (mr *MockSQLFactoryMockRecorder) GetUpdateJobStatusQuerySQL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdateJobStatusQuerySQL", reflect.TypeOf((*MockSQLFactory)(nil).GetUpdateJobStatusQuerySQL))
}

// GetUpdateJobStatusUpdateSQL mocks base method.
func (m *MockSQLFactory) GetUpdateJobStatusUpdateSQL(fields []string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdateJobStatusUpdateSQL", fields)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUpdateJobStatusUpdateSQL indicates an expected call of GetUpdateJobStatusUpdateSQL.
func (mr *MockSQLFactoryMockRecorder) GetUpdateJobStatusUpdateSQL(fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdateJobStatusUpdateSQL", reflect.TypeOf((*MockSQLFactory)(nil).GetUpdateJobStatusUpdateSQL), fields)
}

// InsertJobSQL mocks base method.
func (m *MockSQLFactory) InsertJobSQL(fields []string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertJobSQL", fields)
	ret0, _ := ret[0].(string)
	return ret0
}

// InsertJobSQL indicates an expected call of InsertJobSQL.
func (mr *MockSQLFactoryMockRecorder) InsertJobSQL(fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertJobSQL", reflect.TypeOf((*MockSQLFactory)(nil).InsertJobSQL), fields)
}

// IsEmpty mocks base method.
func (m *MockSQLFactory) IsEmpty(value any) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmpty", value)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEmpty indicates an expected call of IsEmpty.
func (mr *MockSQLFactoryMockRecorder) IsEmpty(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmpty", reflect.TypeOf((*MockSQLFactory)(nil).IsEmpty), value)
}

// IsParameterInject mocks base method.
func (m *MockSQLFactory) IsParameterInject(params map[string]string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsParameterInject", params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// IsParameterInject indicates an expected call of IsParameterInject.
func (mr *MockSQLFactoryMockRecorder) IsParameterInject(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsParameterInject", reflect.TypeOf((*MockSQLFactory)(nil).IsParameterInject), params)
}

// UpdateJobSQL mocks base method.
func (m *MockSQLFactory) UpdateJobSQL(fields []string, value []any, visitor common.Visitor) (string, []any) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobSQL", fields, value, visitor)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	return ret0, ret1
}

// UpdateJobSQL indicates an expected call of UpdateJobSQL.
func (mr *MockSQLFactoryMockRecorder) UpdateJobSQL(fields, value, visitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobSQL", reflect.TypeOf((*MockSQLFactory)(nil).UpdateJobSQL), fields, value, visitor)
}
