// Code generated by MockGen. DO NOT EDIT.
// Source: ../utils/db.go
//
// Generated by this command:
//
//	mockgen -package mock -source ../utils/db.go -destination ../mock/mock_db.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	common "github.com/kweaver-ai/kweaver-core/adp/dataflow/flow-automation/pkg/ecron/common"
	gomock "go.uber.org/mock/gomock"
)

// MockDBClient is a mock of DBClient interface.
type MockDBClient struct {
	ctrl     *gomock.Controller
	recorder *MockDBClientMockRecorder
	isgomock struct{}
}

// MockDBClientMockRecorder is the mock recorder for MockDBClient.
type MockDBClientMockRecorder struct {
	mock *MockDBClient
}

// NewMockDBClient creates a new mock instance.
func NewMockDBClient(ctrl *gomock.Controller) *MockDBClient {
	mock := &MockDBClient{ctrl: ctrl}
	mock.recorder = &MockDBClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBClient) EXPECT() *MockDBClientMockRecorder {
	return m.recorder
}

// BatchJobEnable mocks base method.
func (m *MockDBClient) BatchJobEnable(jobID []string, enable bool, updateTime string, visitor common.Visitor) *common.ECronError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchJobEnable", jobID, enable, updateTime, visitor)
	ret0, _ := ret[0].(*common.ECronError)
	return ret0
}

// BatchJobEnable indicates an expected call of BatchJobEnable.
func (mr *MockDBClientMockRecorder) BatchJobEnable(jobID, enable, updateTime, visitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchJobEnable", reflect.TypeOf((*MockDBClient)(nil).BatchJobEnable), jobID, enable, updateTime, visitor)
}

// BatchJobNotify mocks base method.
func (m *MockDBClient) BatchJobNotify(jobID []string, notify common.JobNotify, updatetime string, visitor common.Visitor) ([]string, *common.ECronError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchJobNotify", jobID, notify, updatetime, visitor)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(*common.ECronError)
	return ret0, ret1
}

// BatchJobNotify indicates an expected call of BatchJobNotify.
func (mr *MockDBClientMockRecorder) BatchJobNotify(jobID, notify, updatetime, visitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchJobNotify", reflect.TypeOf((*MockDBClient)(nil).BatchJobNotify), jobID, notify, updatetime, visitor)
}

// CheckJobExecuteMode mocks base method.
func (m *MockDBClient) CheckJobExecuteMode(executeMode string) *common.ECronError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckJobExecuteMode", executeMode)
	ret0, _ := ret[0].(*common.ECronError)
	return ret0
}

// CheckJobExecuteMode indicates an expected call of CheckJobExecuteMode.
func (mr *MockDBClientMockRecorder) CheckJobExecuteMode(executeMode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckJobExecuteMode", reflect.TypeOf((*MockDBClient)(nil).CheckJobExecuteMode), executeMode)
}

// Connect mocks base method.
func (m *MockDBClient) Connect() *common.ECronError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(*common.ECronError)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockDBClientMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockDBClient)(nil).Connect))
}

// DeleteJob mocks base method.
func (m *MockDBClient) DeleteJob(jobID string, visitor common.Visitor) *common.ECronError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJob", jobID, visitor)
	ret0, _ := ret[0].(*common.ECronError)
	return ret0
}

// DeleteJob indicates an expected call of DeleteJob.
func (mr *MockDBClientMockRecorder) DeleteJob(jobID, visitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJob", reflect.TypeOf((*MockDBClient)(nil).DeleteJob), jobID, visitor)
}

// GetJob mocks base method.
func (m *MockDBClient) GetJob(params common.JobInfoQueryParams, visitor common.Visitor) ([]common.JobInfo, *common.ECronError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", params, visitor)
	ret0, _ := ret[0].([]common.JobInfo)
	ret1, _ := ret[1].(*common.ECronError)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob.
func (mr *MockDBClientMockRecorder) GetJob(params, visitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockDBClient)(nil).GetJob), params, visitor)
}

// GetJobStatus mocks base method.
func (m *MockDBClient) GetJobStatus(params common.JobStatusQueryParams, visitor common.Visitor) ([]common.JobStatus, *common.ECronError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobStatus", params, visitor)
	ret0, _ := ret[0].([]common.JobStatus)
	ret1, _ := ret[1].(*common.ECronError)
	return ret0, ret1
}

// GetJobStatus indicates an expected call of GetJobStatus.
func (mr *MockDBClientMockRecorder) GetJobStatus(params, visitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobStatus", reflect.TypeOf((*MockDBClient)(nil).GetJobStatus), params, visitor)
}

// GetJobTotal mocks base method.
func (m *MockDBClient) GetJobTotal(params common.JobTotalQueryParams, visitor common.Visitor) (common.JobTotal, *common.ECronError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobTotal", params, visitor)
	ret0, _ := ret[0].(common.JobTotal)
	ret1, _ := ret[1].(*common.ECronError)
	return ret0, ret1
}

// GetJobTotal indicates an expected call of GetJobTotal.
func (mr *MockDBClientMockRecorder) GetJobTotal(params, visitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobTotal", reflect.TypeOf((*MockDBClient)(nil).GetJobTotal), params, visitor)
}

// InsertJob mocks base method.
func (m *MockDBClient) InsertJob(job common.JobInfo, visitor common.Visitor) *common.ECronError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertJob", job, visitor)
	ret0, _ := ret[0].(*common.ECronError)
	return ret0
}

// InsertJob indicates an expected call of InsertJob.
func (mr *MockDBClientMockRecorder) InsertJob(job, visitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertJob", reflect.TypeOf((*MockDBClient)(nil).InsertJob), job, visitor)
}

// Ping mocks base method.
func (m *MockDBClient) Ping() *common.ECronError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(*common.ECronError)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDBClientMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDBClient)(nil).Ping))
}

// Release mocks base method.
func (m *MockDBClient) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockDBClientMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockDBClient)(nil).Release))
}

// UpdateJob mocks base method.
func (m *MockDBClient) UpdateJob(job common.JobInfo, visitor common.Visitor) *common.ECronError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJob", job, visitor)
	ret0, _ := ret[0].(*common.ECronError)
	return ret0
}

// UpdateJob indicates an expected call of UpdateJob.
func (mr *MockDBClientMockRecorder) UpdateJob(job, visitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJob", reflect.TypeOf((*MockDBClient)(nil).UpdateJob), job, visitor)
}

// UpdateJobStatus mocks base method.
func (m *MockDBClient) UpdateJobStatus(status []common.JobStatus, visitor common.Visitor) ([]string, *common.ECronError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobStatus", status, visitor)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(*common.ECronError)
	return ret0, ret1
}

// UpdateJobStatus indicates an expected call of UpdateJobStatus.
func (mr *MockDBClientMockRecorder) UpdateJobStatus(status, visitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobStatus", reflect.TypeOf((*MockDBClient)(nil).UpdateJobStatus), status, visitor)
}

// Upgrade mocks base method.
func (m *MockDBClient) Upgrade() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Upgrade")
}

// Upgrade indicates an expected call of Upgrade.
func (mr *MockDBClientMockRecorder) Upgrade() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upgrade", reflect.TypeOf((*MockDBClient)(nil).Upgrade))
}
