// Code generated by MockGen. DO NOT EDIT.
// Source: httpserver_interface.go
//
// Generated by this command:
//
//	mockgen -package mock -source httpserver_interface.go -destination ../mock/mock_httpserver.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	common "github.com/kweaver-ai/kweaver-core/adp/dataflow/flow-automation/pkg/ecron/common"
	gomock "go.uber.org/mock/gomock"
)

// MockHTTPServerStarter is a mock of HTTPServerStarter interface.
type MockHTTPServerStarter struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPServerStarterMockRecorder
	isgomock struct{}
}

// MockHTTPServerStarterMockRecorder is the mock recorder for MockHTTPServerStarter.
type MockHTTPServerStarterMockRecorder struct {
	mock *MockHTTPServerStarter
}

// NewMockHTTPServerStarter creates a new mock instance.
func NewMockHTTPServerStarter(ctrl *gomock.Controller) *MockHTTPServerStarter {
	mock := &MockHTTPServerStarter{ctrl: ctrl}
	mock.recorder = &MockHTTPServerStarterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPServerStarter) EXPECT() *MockHTTPServerStarterMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockHTTPServerStarter) Start(svr common.ServerInfo, handlers map[string][]map[string]func(*gin.Context)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", svr, handlers)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockHTTPServerStarterMockRecorder) Start(svr, handlers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockHTTPServerStarter)(nil).Start), svr, handlers)
}
